---
title: "Conclusion"
author: "Ghislaine de Groot"
date: "2025-11-07"
output: html_document
bibliography: references.bib
---

# Conclusion
The aim of this paper was to examine whether prestige, specifically when differentiating between individual and departmental prestige, had a significant influence on the formation of collaboration networks among Dutch sociologists. To address this research problem, I will answer the following research questions.

RQ 1: To what extent do Dutch sociology departments differ in prestige?

Based on the mean h-index of the sociology professors, which I operationalised as academic prestige for this paper, there are differences between Dutch sociology departments. H-index is a way to measure the individual academic output of a researcher, and looking at literature of network stars, academics who collaborate with highly productive academics also enjoy more academic success. Sociology departments in the Netherlands differ in the average h-index of their senior staff, but the distribution does not range too considerably.

RQ 2: To what extent do Dutch sociologists want to collaborate with other Dutch sociologists who have more prestige than themselves?
RQ 3: To what extent does departmental prestige matter more than individual prestige in the collaboration network of Dutch sociologists?

This research has found no indication that prestige matters in the establishment of collaborations to write a paper together. Dutch sociologists appear to be very versatile in their collaborations, as prestige, either individual or departmental, as well as university of employment and certainly not gender did not matter in this analysis. This finding seems to echo Katz & Martin (@KatzMartin1997), who propose, among their many suggestions for how scientific collaboration is established, that spatial proximity is also less important when there is a clear division of tasks required for a research project, leading academics to seek out experts, even if they have to travel some distance to find them. Expertise seems fragmented among the seven Dutch sociology departments, and may be one of the more important factors in collaboration among sociologists. If more ‘formal’ attachments such as place of employment are less relevant for scholarly work, and expertise is more important, then chances are that the formation of informal ties (Morehouse & Saffer), such as friendships formed on strongly aligning research interests, matters more in the context of this population. To better understand the collaborations between Dutch sociologists, this idea could be pursued in future research. 
Notwithstanding the Dutch context, prestige has previously been found to influence academic collaborations, and may still be relevant outside of the scope of this paper. Future research should widen the scope of the dataset. Academic collaborations occur in an international context. A prestigious scholar in the Netherlands can link with other scholars who have similar or even more name recognition. As this study suggests that prestige matters little to nothing to collaborations in the Netherlands, it may be due to the similar level of prestige, or due to differences in research interest [@Haan2014]. In an international context, larger differences in (perceived) prestige may be more important, as seen in previous literature on the US [@Burris2004, @Moody2004] and Romania [@Hancean2014]. 
Finally, several limitations should be noted. Firstly, the use of h-index as proxy for prestige is a one-dimensional measure for a multidimensional concept, and this simplification may have led to a skewed interpretation of prestige. There are several different measures which could be used together to form a more robust measure of academic output. Secondly, the operationalisation of sender and receiver of a tie in this network is based on first authorship. Most senior staff let junior staff be first author(s) to improve the latter’s academic capital, as the senior staff already have more credit to their name. Therefore, how ties were used in this paper may obscure actual practices between academics.

