---
title: "Introduction"
author: "Ghislaine de Groot"
date: "2025-11-07"
output: html_document
bibliography: references.bib
---
# Introduction

Despite the image of academia as an ivory tower removed from society, research universities are subject to similar, if not the same, social processes that govern the organisation of work and labour elsewhere. The work of one university or university department is valued differently (and unequally), consequently having different levels of prestige. This may indicate stratification of status between universities and departments, which extends to social mobility and promotion opportunities. Stratification determines inequalities between individuals and groups of people, where prestigious positions become inaccessible to those who do not have the right social connections, instead of being accessible through merit alone.
    
In countries with a larger number of sociology departments, stark differences in quality can occur, such as the United States of America [@Moody2004], [@Burris2004] and Romania [@Hancean2014]. Earlier research in the USA [@Burris2004] showed that sociologists across the 94 US departments formed castes at the top 5%, where those who started at a top-level university stay employed at top-level universities, creating a tightly knit group of collaborators. Members of high-level universities only collaborating with each other follows the general trend of homophily in work relationships, where academics are expected to work together with those who share a similar social background and are spatially close to one another [@KatzMartin1997]. Katz and Martin (1997) also point out that this trend of similarity has exceptions, but do not elaborate much on this statement. In this research, I will attempt to find a pattern for when collaborations follow a pattern of heterophily, i.e. dissimilarity between the collaborating academics, specifically studying differences in prestige at several levels is the most promising. The departments themselves can hold a certain social status, which then impacts academic careers of the employed researchers. The more prestigious the institution is, the higher the productivity of the researcher is (see @Way2017 for a literature review). Previous research has also shown that collaboration can improve productivity [@KatzMartin1997]. Taking these two statements together, if academics would want to maximise their productivity, they would have to 1) collaborate 2) with an academic from a more prestigious institute than themselves.

While much research has already been dedicated to the influence of prestige on scientific collaborations, this field has yet to examine individual prestige versus departmental prestige. It could yield important nuances to how prestige functions in academia, as well as give insight to stratification and the reproduction of inequality between universities. [@Burris2004] studied only departmental prestige, whereas I will include both the prestige level of the individual sociologist and the prestige level of the department individual sociologists are employed at.

Funding can impact the quality of the department. If the department has little room to grow and accumulate academic capital, chances are that they cannot prove themselves, and cannot get more funding as a result, which will result in missing out on prestige improvement [@Larregue2025]. 

Science collaboration is an extensive field of study, but the literature has yet to cover the Netherlands, in spite of the importance of Dutch sociology on the international playing field [@RU2020].   

I will examine whether there is a significant difference in prestige between the sociology departments, and how that affects the collaboration networks of sociologists. My aim is to research whether this prestige has an impact on collaboration, which could stratify the quality of research output. As I want to map how sociologists are connected together and have different types and strengths of connections, I will conduct social network analysis. The underlying question is whether academics, in this case sociologists, send collaboration invitations on the basis of another sociologist's own academic output, or on the basis of status by association.

RQ 1: To what extent do Dutch sociology departments differ in prestige?

RQ 2: To what extent do Dutch sociologists want to collaborate with other Dutch sociologists who have more prestige than themselves?

RQ 3: To what extent does departmental prestige matter more than individual prestige in the collaboration network of Dutch sociologists?

