---
title: "Journal 2"
author: "Ghislaine de Groot"
bibliography: references.bib
---



```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
#rgl::setupKnitr()



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

Last compiled on `r format(Sys.time(), '%B, %Y')`

<br>

----
  
This is just an example page of your `r colorize("lab journal", "red")`.
You can journal the assignments of the second day here.
  

----

# Seminar 2

_Network description_


## Things I did in class

Found out how to add a new page.

## Things I did outside of class

Read the literature.

Reconfigured my research topic, and wrote the introduction based on my new questions.

----


```{r}



numbers <- round(runif(10000), 0)

fake <- matrix(data = numbers, nrow = 100, ncol = 100, byrow = FALSE,
       dimnames = NULL)

diag(fake) <- 0

rowSums(fake)

mean(fake)

# Transposing the matrix
transposed_fake <- t(fake)
print(fake)

sum(fake, na.rm = FALSE)

```

```{r}
library(tidyr)
```

```{r}
numbers <- round(runif(10000), 0)

small <- matrix(data = numbers, nrow = 4, ncol = 4, byrow = FALSE,
       dimnames = NULL)
print(small)

diag(small) <- 0
print(small)

trans_small <- t(small)

very_small <- small + trans_small

very_small <- ifelse(very_small==2,1,0)
```


```{r}
numbers <- round(runif(10000), 0)

medium <- matrix(data = numbers, nrow = 5, ncol = 5, byrow = FALSE,
       dimnames = NULL)

diag(medium) <- 0

trans_medium <- t(medium)

very_medium <- medium + trans_medium

very_medium <- ifelse(very_medium==2, 1,0)
```


```{r}
install.packages("igraph")
library(igraph)

set.seed(123643)
network1 <- matrix(sample(0:1, 16, replace = TRUE), nrow = 4, ncol = 4, byrow = FALSE,
       dimnames = NULL)

net_un <- network1 + t(network1)

net_un <- ifelse(net_un==2,1,
                 ifelse(1,1,0))

diag(net_un) <- 0

netGraph <- graph_from_adjacency_matrix(net_un)
class(netGraph)
plot(netGraph)
igraph::transitivity(netGraph, type = "undirected") 
netGraph

dyad_census(netGraph)

?igraph

netGraph_di <- graph_from_adjacency_matrix(network1)
class(netGraph_di)
plot(netGraph_di)
igraph::transitivity(netGraph_di, type = "directed") 

triad_census(netGraph)
```


```{r}
install.packages("sna")

bignumbers <- round(runif(10000), 0)

big <- matrix(data = bignumbers, nrow = 10, ncol = 10, byrow = FALSE,
       dimnames = NULL)

big_un <- big + t(big)

big_un <- ifelse(big_un==2,1,
                 ifelse(1,1,0))

diag(big_un) <- 0

bigGraph <- graph_from_adjacency_matrix(big_un)
class(bigGraph)
plot(bigGraph)
igraph::transitivity(bigGraph, type = "undirected")
```


```{r}

library(foreign)

LISS <- read.rdata('/Users/ghislaine/Downloads/Uni RU/Social Networks/partner_dataprepped.Rdata')

```
```{r}
install.packages("formatR")
library(formatR)
```
