---
title: "Theory"
author: "Ghislaine de Groot"
date: "2025-11-07"
output: html_document
bibliography: references.bib
---

# Theory

To set the stage, it is important to not uncritically adopt the term ‘research collaboration’ before setting a definition (Katz & Martin, 1997). In line with most of the literature (Katz & Martin, 1997), I will define a collaboration as a paper which multiple authors have written, regardless of the workload distribution (e.g. Melin & Presson, 1996). This definition will aid in explaining why academics follow certain patterns in engaging in collaborations. 

Collaboration has been found to positively impact the productivity of academics (Katz & Martin, 1997), and a higher productivity results in higher prestige (Way et al., 2017). Katz and Martin (1997) suggest that while collaborations with peers are generally more likely to occur than collaborations between academics of unequal rank, they add that “this is by no means always the case” (p. 5). For example, Hagstrom (1971) mentions student-teacher collaborations as an unequal dynamic.

Within the extensive literature on co-authorships in the social sciences, several collaboration structures have been empirically identified. Small world networks and structural cohesion are two of those, but given my interest in differences between sociologists based on their own ‘capital’, the principle of preferential attachment is more fitting to test my hypotheses with. As outlined by Barabási and Albert (1999) in their paper on random networks with a complex topology, the principle of preferential attachment was one such collaboration structure [@Moody2004], [@Mali2012]. This principle assumes that “new links and nodes are not randomly connected to large networks, but based on observed power-law distributions" ([@Hancean2014], p.2). In the context of scientific collaboration networks, this means that personal achievements (e.g. obtaining academic credentials) are cumulative, and through gaining academic prestige, scientists gain more power and the scientific network shapes around them. Prestige can therefore be seen as cultural or symbolic capital, which are advantageous resources such as credentials that can determine social status (Bourdieu, 1986). Merton (1968) called this the Matthew-effect. These highly prestigious scholars can become very influential in their field, or shape the field around them. Very prestigious scholars should be considered as star nodes in their network. Stars ‘receive’ more invitations to form a connection than they ‘send’ themselves [@Knoke2011]. Other academics would want to form a tie with star researchers to improve their own academic standing.

H1: Sociologists prefer working with another sociologist with higher prestige than themselves

While it would be idealistic that academics are viewed only by their own merit, who they are associated with (i.e. their position in the network) may have a direct influence on how they, and thus their quality and status, are perceived. Cultural and symbolic capital could also be obtained during one’s career, from affiliation with the university or department of employment. Past studies have found that researchers at more prestigious institutions tend to be more productive (see Way et al, 2017 for a literature review), which reproduces the prestige of individual academics. 

Departments and their respective universities deal with inequalities relating to the allocation of resources such as funds (see Larregue, 2015). Prestige works as stratification, where more prestigious academics or academic groups get more funding, becoming more productive in producing output that meet certain standards, thereby receiving more funding. It is a limited pool of resources that less prestigious departments do not receive, either within the university as a whole or between departments of the same discipline. 

If there is an effect of departmental prestige on the formation of interuniversity collaboration networks present, then it would also be reflected on the individual level. Sociologists who have lower prestige could then benefit from the collective prestige of their department. They would experience spillover prestige (Bandelj, 2019) or being basked in reflected glory (Cialdini et al., 1976). 

Star researchers can greatly contribute to their overall departmental prestige. Previous research shows that collaborations are generally expected to occur within the same workspace (Katz & Martin, 1997), such as a department. If the collaboration with the star researcher leads to higher productivity with the collaborator, measured for example through the number of publications (Way et al., 2017), the department as a whole is represented through that work.  

H2. Sociologists prefer working with another sociologist with higher departmental prestige than themselves, despite the other having lower individual prestige than themselves.

With Hypothesis 2, it can either indicate that a sociologist has an equal or higher h-index than the department mean, or the sociologist in question has a lower h-index than the mean and can benefit from the department’s prestige.  

While I am assuming that collaborations are enacted based on differences in prestige, I should take another important finding of previous literature into account. This finding is that academics generally collaborate based on shared similarities. Spatial proximity, such as working at the same department, is one such similarity. Katz (1993) found that co-authorship exponentially decreases when physical distance between the institutions at which researchers are employed increases. Not only are departmental colleagues more easily available, but they are also more likely to share assumptions and preferences in how to do research, as departments differ in specialisation and research interests (de Haan, 2012). The importance of spatial proximity has been waning over time, with the implementation of technology in the workplace, such as writing emails, making it easier to keep in touch, exchange ideas and distribute tasks (Hunter & Leahey, 2008). New avenues are opened up to more easily initiate interuniversity collaboration.
Besides physical distance, social distance is another important factor. “In general, collaboration between peers (i.e., scientists of similar standing) is more likely than collaboration between individuals of unequal rank” (Katz & Martin 1997, p. 5). This homophily principle (McPherson et al., 2001) will be tested using gender, where it is expected that an academic is more likely to seek collaborations with someone with the same gender than seek an academic who does not have the same gender. 

H3a: Sociologists collaborate with other sociologists who work at the department at the same time.
H3b: Sociologists collaborate with other sociologists who share the same gender.
 